version: '3'

services:
  ac_python:
    build: .
    image: mollinaca/personal:ac_python
    restart: 'no'
    container_name: 'ac_python'
    working_dir: '/root/ac/'
    tty: true
    volumes:
      - ./code:/root/code
